# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("http://automationpractice.com/index.php")
    self.driver.set_window_size(550, 692)
    self.driver.find_element(By.LINK_TEXT, "Sign out").click()
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("newtest@mail.ru")
    self.driver.find_element(By.ID, "passwd").send_keys("qwe1@3RTY")
    self.driver.find_element(By.CSS_SELECTOR, "#SubmitLogin > span").click()
    self.driver.find_element(By.ID, "search_query_top").click()
    self.driver.find_element(By.ID, "search_query_top").send_keys("shirt")
    self.driver.find_element(By.NAME, "submit_search").click()
    self.driver.find_element(By.LINK_TEXT, "Sign out").click()
    self.driver.close()
  
